package audit

import (
	"fmt"
	"strings"
	"time"

	"github.com/kubewise/kubewise/internal/audit/domain"
)

func RenderMarkdown(cluster string, findings []domain.Finding, summary domain.Summary, auditedAt time.Time, durationMs int64) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("# KubeWise Security Audit — %s\n\n", cluster))
	b.WriteString(fmt.Sprintf("**Audited:** %s UTC  \n", auditedAt.UTC().Format("2006-01-02 15:04")))
	b.WriteString(fmt.Sprintf("**Duration:** %ds  \n", durationMs/1000))
	b.WriteString(fmt.Sprintf("**Findings:** %d (Critical %d · High %d · Medium %d · Low %d)\n\n",
		summary.Total, summary.Critical, summary.High, summary.Medium, summary.Low))

	order := []domain.Severity{
		domain.SeverityCritical, domain.SeverityHigh, domain.SeverityMedium, domain.SeverityLow,
	}
	labels := map[domain.Severity]string{
		domain.SeverityCritical: "Critical",
		domain.SeverityHigh:     "High",
		domain.SeverityMedium:   "Medium",
		domain.SeverityLow:      "Low",
	}
	for _, sev := range order {
		group := filterBySeverity(findings, sev)
		if len(group) == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf("## %s\n\n", labels[sev]))
		for _, f := range group {
			b.WriteString(fmt.Sprintf("### %s — %s\n\n", f.Category, f.Resource))
			b.WriteString(fmt.Sprintf("- **Risk:** %s\n", f.Risk))
			b.WriteString(fmt.Sprintf("- **Impact:** %s\n", f.Impact))
			b.WriteString(fmt.Sprintf("- **Suggestion:** %s\n\n", f.Suggestion))
		}
	}
	if summary.Total == 0 {
		b.WriteString("No security findings detected.\n")
	}
	b.WriteString("\n---\n_Generated by KubeWise Security Scanner_\n")
	return b.String()
}

func filterBySeverity(findings []domain.Finding, sev domain.Severity) []domain.Finding {
	var out []domain.Finding
	for _, f := range findings {
		if f.Severity == sev {
			out = append(out, f)
		}
	}
	return out
}
